#############################################################################
# Makefile for building: SecureInternetRelayChat_Server
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  SecureInternetRelayChat_Server.pro
# Template: app
# Command: /home/roman/Qt/5.8/gcc_64/bin/qmake -o Makefile SecureInternetRelayChat_Server.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++14 -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt/5.8/gcc_64/include -I../../Qt/5.8/gcc_64/include/QtNetwork -I../../Qt/5.8/gcc_64/include/QtCore -I. -I../../Qt/5.8/gcc_64/mkspecs/linux-g++
QMAKE         = /home/roman/Qt/5.8/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SecureInternetRelayChat_Server1.0.0
DISTDIR = /home/roman/pb173_project/secure-internet-relay-chat-server/.tmp/SecureInternetRelayChat_Server1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/roman/Qt/5.8/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/roman/Qt/5.8/gcc_64/lib -lQt5Network -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Server.cpp \
		Connection.cpp \
		clientinfo.cpp \
		gcmutils.cpp \
		securityfunctions.cpp \
		libs/aes.c \
		libs/aesni.c \
		libs/gcm.c \
		libs/sha512.c \
		libs/cipher.c \
		libs/padlock.c \
		libs/platform.c \
		libs/ccm.c \
		libs/cmac.c \
		libs/cipher_wrap.c \
		libs/arc4.c \
		libs/camellia.c \
		libs/blowfish.c \
		libs/des.c \
		libs/threading.c \
		libs/entropy_poll.c \
		libs/ctr_drbg.c \
		libs/timing.c \
		libs/havege.c \
		libs/entropy.c \
		libs/bignum.c \
		libs/ripemd160.c \
		libs/sha1.c \
		libs/sha256.c \
		libs/md2.c \
		libs/md4.c \
		libs/md5.c \
		libs/md_wrap.c \
		libs/asn1parse.c \
		libs/md.c \
		libs/oid.c \
		libs/rsa.c \
		rsautils.cpp \
		buffer.cpp \
		parser.cpp moc_Connection.cpp \
		moc_Server.cpp
OBJECTS       = main.o \
		Server.o \
		Connection.o \
		clientinfo.o \
		gcmutils.o \
		securityfunctions.o \
		aes.o \
		aesni.o \
		gcm.o \
		sha512.o \
		cipher.o \
		padlock.o \
		platform.o \
		ccm.o \
		cmac.o \
		cipher_wrap.o \
		arc4.o \
		camellia.o \
		blowfish.o \
		des.o \
		threading.o \
		entropy_poll.o \
		ctr_drbg.o \
		timing.o \
		havege.o \
		entropy.o \
		bignum.o \
		ripemd160.o \
		sha1.o \
		sha256.o \
		md2.o \
		md4.o \
		md5.o \
		md_wrap.o \
		asn1parse.o \
		md.o \
		oid.o \
		rsa.o \
		rsautils.o \
		buffer.o \
		parser.o \
		moc_Connection.o \
		moc_Server.o
DIST          = ../../Qt/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.8/gcc_64/mkspecs/common/unix.conf \
		../../Qt/5.8/gcc_64/mkspecs/common/linux.conf \
		../../Qt/5.8/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/5.8/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/5.8/gcc_64/mkspecs/qconfig.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/5.8/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/toolchain.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/qt.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/resources.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/moc.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/lex.prf \
		SecureInternetRelayChat_Server.pro Connection.h \
		clientinfo.h \
		catch.hpp \
		gcmutils.h \
		securityfunctions.h \
		libs/cipher_internal.h \
		libs/aes.h \
		libs/aesni.h \
		libs/gcm.h \
		libs/sha512.h \
		libs/check_config.h \
		libs/cipher.h \
		libs/config.h \
		libs/padlock.h \
		libs/platform.h \
		libs/platform_time.h \
		libs/target_config.h \
		catch.hpp \
		libs/ccm.h \
		libs/cmac.h \
		libs/arc4.h \
		libs/camellia.h \
		libs/blowfish.h \
		libs/des.h \
		libs/threading.h \
		libs/entropy_poll.h \
		libs/ctr_drbg.h \
		libs/timing.h \
		libs/havege.h \
		libs/entropy.h \
		libs/bignum.h \
		libs/ripemd160.h \
		libs/sha1.h \
		libs/sha256.h \
		libs/md2.h \
		libs/md4.h \
		libs/md5.h \
		libs/md_internal.h \
		libs/asn1.h \
		libs/md.h \
		libs/oid.h \
		libs/rsa.h \
		rsautils.h \
		buffer.h \
		parser.h \
		Server.h main.cpp \
		Server.cpp \
		Connection.cpp \
		clientinfo.cpp \
		gcmutils.cpp \
		securityfunctions.cpp \
		libs/aes.c \
		libs/aesni.c \
		libs/gcm.c \
		libs/sha512.c \
		libs/cipher.c \
		libs/padlock.c \
		libs/platform.c \
		libs/ccm.c \
		libs/cmac.c \
		libs/cipher_wrap.c \
		libs/arc4.c \
		libs/camellia.c \
		libs/blowfish.c \
		libs/des.c \
		libs/threading.c \
		libs/entropy_poll.c \
		libs/ctr_drbg.c \
		libs/timing.c \
		libs/havege.c \
		libs/entropy.c \
		libs/bignum.c \
		libs/ripemd160.c \
		libs/sha1.c \
		libs/sha256.c \
		libs/md2.c \
		libs/md4.c \
		libs/md5.c \
		libs/md_wrap.c \
		libs/asn1parse.c \
		libs/md.c \
		libs/oid.c \
		libs/rsa.c \
		rsautils.cpp \
		buffer.cpp \
		parser.cpp
QMAKE_TARGET  = SecureInternetRelayChat_Server
DESTDIR       = 
TARGET        = SecureInternetRelayChat_Server


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SecureInternetRelayChat_Server.pro ../../Qt/5.8/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.8/gcc_64/mkspecs/common/unix.conf \
		../../Qt/5.8/gcc_64/mkspecs/common/linux.conf \
		../../Qt/5.8/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/5.8/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/5.8/gcc_64/mkspecs/qconfig.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/5.8/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/toolchain.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/qt.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/resources.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/moc.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/5.8/gcc_64/mkspecs/features/lex.prf \
		SecureInternetRelayChat_Server.pro \
		../../Qt/5.8/gcc_64/lib/libQt5Network.prl \
		../../Qt/5.8/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile SecureInternetRelayChat_Server.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../../Qt/5.8/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt/5.8/gcc_64/mkspecs/common/unix.conf:
../../Qt/5.8/gcc_64/mkspecs/common/linux.conf:
../../Qt/5.8/gcc_64/mkspecs/common/sanitize.conf:
../../Qt/5.8/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt/5.8/gcc_64/mkspecs/common/g++-base.conf:
../../Qt/5.8/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt/5.8/gcc_64/mkspecs/qconfig.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.8/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt/5.8/gcc_64/mkspecs/features/qt_config.prf:
../../Qt/5.8/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt/5.8/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.8/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.8/gcc_64/mkspecs/features/toolchain.prf:
../../Qt/5.8/gcc_64/mkspecs/features/default_pre.prf:
../../Qt/5.8/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt/5.8/gcc_64/mkspecs/features/default_post.prf:
../../Qt/5.8/gcc_64/mkspecs/features/qml_debug.prf:
../../Qt/5.8/gcc_64/mkspecs/features/warn_on.prf:
../../Qt/5.8/gcc_64/mkspecs/features/qt.prf:
../../Qt/5.8/gcc_64/mkspecs/features/resources.prf:
../../Qt/5.8/gcc_64/mkspecs/features/moc.prf:
../../Qt/5.8/gcc_64/mkspecs/features/unix/thread.prf:
../../Qt/5.8/gcc_64/mkspecs/features/qmake_use.prf:
../../Qt/5.8/gcc_64/mkspecs/features/file_copies.prf:
../../Qt/5.8/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.8/gcc_64/mkspecs/features/exceptions.prf:
../../Qt/5.8/gcc_64/mkspecs/features/yacc.prf:
../../Qt/5.8/gcc_64/mkspecs/features/lex.prf:
SecureInternetRelayChat_Server.pro:
../../Qt/5.8/gcc_64/lib/libQt5Network.prl:
../../Qt/5.8/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile SecureInternetRelayChat_Server.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt/5.8/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Connection.h clientinfo.h catch.hpp gcmutils.h securityfunctions.h libs/cipher_internal.h libs/aes.h libs/aesni.h libs/gcm.h libs/sha512.h libs/check_config.h libs/cipher.h libs/config.h libs/padlock.h libs/platform.h libs/platform_time.h libs/target_config.h catch.hpp libs/ccm.h libs/cmac.h libs/arc4.h libs/camellia.h libs/blowfish.h libs/des.h libs/threading.h libs/entropy_poll.h libs/ctr_drbg.h libs/timing.h libs/havege.h libs/entropy.h libs/bignum.h libs/ripemd160.h libs/sha1.h libs/sha256.h libs/md2.h libs/md4.h libs/md5.h libs/md_internal.h libs/asn1.h libs/md.h libs/oid.h libs/rsa.h rsautils.h buffer.h parser.h Server.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp Server.cpp Connection.cpp clientinfo.cpp gcmutils.cpp securityfunctions.cpp libs/aes.c libs/aesni.c libs/gcm.c libs/sha512.c libs/cipher.c libs/padlock.c libs/platform.c libs/ccm.c libs/cmac.c libs/cipher_wrap.c libs/arc4.c libs/camellia.c libs/blowfish.c libs/des.c libs/threading.c libs/entropy_poll.c libs/ctr_drbg.c libs/timing.c libs/havege.c libs/entropy.c libs/bignum.c libs/ripemd160.c libs/sha1.c libs/sha256.c libs/md2.c libs/md4.c libs/md5.c libs/md_wrap.c libs/asn1parse.c libs/md.c libs/oid.c libs/rsa.c rsautils.cpp buffer.cpp parser.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt/5.8/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++14 -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../Qt/5.8/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_Connection.cpp moc_Server.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Connection.cpp moc_Server.cpp
moc_Connection.cpp: ../../Qt/5.8/gcc_64/include/QtCore/QObject \
		../../Qt/5.8/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.8/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/QDebug \
		../../Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.8/gcc_64/include/QtCore/qset.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QTcpSocket \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QSslSocket \
		../../Qt/5.8/gcc_64/include/QtNetwork/qsslsocket.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qsslerror.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcryptographichash.h \
		../../Qt/5.8/gcc_64/include/QtCore/qdatetime.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qssl.h \
		../../Qt/5.8/gcc_64/include/QtCore/QFlags \
		../../Qt/5.8/gcc_64/include/QtCore/QFile \
		../../Qt/5.8/gcc_64/include/QtCore/qfile.h \
		../../Qt/5.8/gcc_64/include/QtCore/qfiledevice.h \
		clientinfo.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QHostAddress \
		../../Qt/5.8/gcc_64/include/QtNetwork/qhostaddress.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonDocument \
		../../Qt/5.8/gcc_64/include/QtCore/qjsondocument.h \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonvalue.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonValue \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonArray \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonarray.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonObject \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonobject.h \
		gcmutils.h \
		securityfunctions.h \
		libs/cipher.h \
		libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/aes.h \
		libs/sha512.h \
		libs/gcm.h \
		libs/entropy.h \
		libs/sha256.h \
		libs/threading.h \
		libs/havege.h \
		libs/ctr_drbg.h \
		buffer.h \
		../../Qt/5.8/gcc_64/include/QtCore/QByteArray \
		../../Qt/5.8/gcc_64/include/QtCore/QDataStream \
		../../Qt/5.8/gcc_64/include/QtCore/qdatastream.h \
		parser.h \
		../../Qt/5.8/gcc_64/include/QtCore/QList \
		Server.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QTcpServer \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtcpserver.h \
		../../Qt/5.8/gcc_64/include/QtCore/QThread \
		../../Qt/5.8/gcc_64/include/QtCore/qthread.h \
		Connection.h \
		rsautils.h \
		libs/rsa.h \
		libs/bignum.h \
		libs/md.h \
		Connection.h \
		moc_predefs.h \
		../../Qt/5.8/gcc_64/bin/moc
	/home/roman/Qt/5.8/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/roman/Qt/5.8/gcc_64/mkspecs/linux-g++ -I/home/roman/pb173_project/secure-internet-relay-chat-server -I/home/roman/Qt/5.8/gcc_64/include -I/home/roman/Qt/5.8/gcc_64/include/QtNetwork -I/home/roman/Qt/5.8/gcc_64/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Connection.h -o moc_Connection.cpp

moc_Server.cpp: ../../Qt/5.8/gcc_64/include/QtCore/QObject \
		../../Qt/5.8/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.8/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/QDebug \
		../../Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.8/gcc_64/include/QtCore/qset.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QTcpServer \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtcpserver.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qhostaddress.h \
		../../Qt/5.8/gcc_64/include/QtCore/QThread \
		../../Qt/5.8/gcc_64/include/QtCore/qthread.h \
		Connection.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QTcpSocket \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QSslSocket \
		../../Qt/5.8/gcc_64/include/QtNetwork/qsslsocket.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qsslerror.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcryptographichash.h \
		../../Qt/5.8/gcc_64/include/QtCore/qdatetime.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qssl.h \
		../../Qt/5.8/gcc_64/include/QtCore/QFlags \
		../../Qt/5.8/gcc_64/include/QtCore/QFile \
		../../Qt/5.8/gcc_64/include/QtCore/qfile.h \
		../../Qt/5.8/gcc_64/include/QtCore/qfiledevice.h \
		clientinfo.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QHostAddress \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonDocument \
		../../Qt/5.8/gcc_64/include/QtCore/qjsondocument.h \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonvalue.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonValue \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonArray \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonarray.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonObject \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonobject.h \
		gcmutils.h \
		securityfunctions.h \
		libs/cipher.h \
		libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/aes.h \
		libs/sha512.h \
		libs/gcm.h \
		libs/entropy.h \
		libs/sha256.h \
		libs/threading.h \
		libs/havege.h \
		libs/ctr_drbg.h \
		buffer.h \
		../../Qt/5.8/gcc_64/include/QtCore/QByteArray \
		../../Qt/5.8/gcc_64/include/QtCore/QDataStream \
		../../Qt/5.8/gcc_64/include/QtCore/qdatastream.h \
		parser.h \
		../../Qt/5.8/gcc_64/include/QtCore/QList \
		Server.h \
		rsautils.h \
		libs/rsa.h \
		libs/bignum.h \
		libs/md.h \
		Server.h \
		moc_predefs.h \
		../../Qt/5.8/gcc_64/bin/moc
	/home/roman/Qt/5.8/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/roman/Qt/5.8/gcc_64/mkspecs/linux-g++ -I/home/roman/pb173_project/secure-internet-relay-chat-server -I/home/roman/Qt/5.8/gcc_64/include -I/home/roman/Qt/5.8/gcc_64/include/QtNetwork -I/home/roman/Qt/5.8/gcc_64/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Server.h -o moc_Server.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../Qt/5.8/gcc_64/include/QtCore/QCoreApplication \
		../../Qt/5.8/gcc_64/include/QtCore/qcoreapplication.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.8/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/qeventloop.h \
		Server.h \
		../../Qt/5.8/gcc_64/include/QtCore/QObject \
		../../Qt/5.8/gcc_64/include/QtCore/QDebug \
		../../Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.8/gcc_64/include/QtCore/qset.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QTcpServer \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtcpserver.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qhostaddress.h \
		../../Qt/5.8/gcc_64/include/QtCore/QThread \
		../../Qt/5.8/gcc_64/include/QtCore/qthread.h \
		Connection.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QTcpSocket \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QSslSocket \
		../../Qt/5.8/gcc_64/include/QtNetwork/qsslsocket.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qsslerror.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcryptographichash.h \
		../../Qt/5.8/gcc_64/include/QtCore/qdatetime.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qssl.h \
		../../Qt/5.8/gcc_64/include/QtCore/QFlags \
		../../Qt/5.8/gcc_64/include/QtCore/QFile \
		../../Qt/5.8/gcc_64/include/QtCore/qfile.h \
		../../Qt/5.8/gcc_64/include/QtCore/qfiledevice.h \
		clientinfo.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QHostAddress \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonDocument \
		../../Qt/5.8/gcc_64/include/QtCore/qjsondocument.h \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonvalue.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonValue \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonArray \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonarray.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonObject \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonobject.h \
		gcmutils.h \
		securityfunctions.h \
		libs/cipher.h \
		libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/aes.h \
		libs/sha512.h \
		libs/gcm.h \
		libs/entropy.h \
		libs/sha256.h \
		libs/threading.h \
		libs/havege.h \
		libs/ctr_drbg.h \
		buffer.h \
		../../Qt/5.8/gcc_64/include/QtCore/QByteArray \
		../../Qt/5.8/gcc_64/include/QtCore/QDataStream \
		../../Qt/5.8/gcc_64/include/QtCore/qdatastream.h \
		parser.h \
		../../Qt/5.8/gcc_64/include/QtCore/QList \
		rsautils.h \
		libs/rsa.h \
		libs/bignum.h \
		libs/md.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Server.o: Server.cpp Server.h \
		../../Qt/5.8/gcc_64/include/QtCore/QObject \
		../../Qt/5.8/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.8/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/QDebug \
		../../Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.8/gcc_64/include/QtCore/qset.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QTcpServer \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtcpserver.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qhostaddress.h \
		../../Qt/5.8/gcc_64/include/QtCore/QThread \
		../../Qt/5.8/gcc_64/include/QtCore/qthread.h \
		Connection.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QTcpSocket \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QSslSocket \
		../../Qt/5.8/gcc_64/include/QtNetwork/qsslsocket.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qsslerror.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcryptographichash.h \
		../../Qt/5.8/gcc_64/include/QtCore/qdatetime.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qssl.h \
		../../Qt/5.8/gcc_64/include/QtCore/QFlags \
		../../Qt/5.8/gcc_64/include/QtCore/QFile \
		../../Qt/5.8/gcc_64/include/QtCore/qfile.h \
		../../Qt/5.8/gcc_64/include/QtCore/qfiledevice.h \
		clientinfo.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QHostAddress \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonDocument \
		../../Qt/5.8/gcc_64/include/QtCore/qjsondocument.h \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonvalue.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonValue \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonArray \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonarray.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonObject \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonobject.h \
		gcmutils.h \
		securityfunctions.h \
		libs/cipher.h \
		libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/aes.h \
		libs/sha512.h \
		libs/gcm.h \
		libs/entropy.h \
		libs/sha256.h \
		libs/threading.h \
		libs/havege.h \
		libs/ctr_drbg.h \
		buffer.h \
		../../Qt/5.8/gcc_64/include/QtCore/QByteArray \
		../../Qt/5.8/gcc_64/include/QtCore/QDataStream \
		../../Qt/5.8/gcc_64/include/QtCore/qdatastream.h \
		parser.h \
		../../Qt/5.8/gcc_64/include/QtCore/QList \
		rsautils.h \
		libs/rsa.h \
		libs/bignum.h \
		libs/md.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Server.o Server.cpp

Connection.o: Connection.cpp Connection.h \
		../../Qt/5.8/gcc_64/include/QtCore/QObject \
		../../Qt/5.8/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.8/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/QDebug \
		../../Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.8/gcc_64/include/QtCore/qset.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QTcpSocket \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QSslSocket \
		../../Qt/5.8/gcc_64/include/QtNetwork/qsslsocket.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qsslerror.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qsslcertificate.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcryptographichash.h \
		../../Qt/5.8/gcc_64/include/QtCore/qdatetime.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qssl.h \
		../../Qt/5.8/gcc_64/include/QtCore/QFlags \
		../../Qt/5.8/gcc_64/include/QtCore/QFile \
		../../Qt/5.8/gcc_64/include/QtCore/qfile.h \
		../../Qt/5.8/gcc_64/include/QtCore/qfiledevice.h \
		clientinfo.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QHostAddress \
		../../Qt/5.8/gcc_64/include/QtNetwork/qhostaddress.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonDocument \
		../../Qt/5.8/gcc_64/include/QtCore/qjsondocument.h \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonvalue.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonValue \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonArray \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonarray.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonObject \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonobject.h \
		gcmutils.h \
		securityfunctions.h \
		libs/cipher.h \
		libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/aes.h \
		libs/sha512.h \
		libs/gcm.h \
		libs/entropy.h \
		libs/sha256.h \
		libs/threading.h \
		libs/havege.h \
		libs/ctr_drbg.h \
		buffer.h \
		../../Qt/5.8/gcc_64/include/QtCore/QByteArray \
		../../Qt/5.8/gcc_64/include/QtCore/QDataStream \
		../../Qt/5.8/gcc_64/include/QtCore/qdatastream.h \
		parser.h \
		../../Qt/5.8/gcc_64/include/QtCore/QList \
		Server.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QTcpServer \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtcpserver.h \
		../../Qt/5.8/gcc_64/include/QtCore/QThread \
		../../Qt/5.8/gcc_64/include/QtCore/qthread.h \
		rsautils.h \
		libs/rsa.h \
		libs/bignum.h \
		libs/md.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Connection.o Connection.cpp

clientinfo.o: clientinfo.cpp clientinfo.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QHostAddress \
		../../Qt/5.8/gcc_64/include/QtNetwork/qhostaddress.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.8/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.8/gcc_64/include/QtCore/qset.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonDocument \
		../../Qt/5.8/gcc_64/include/QtCore/qjsondocument.h \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonvalue.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonValue \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonArray \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonarray.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonObject \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientinfo.o clientinfo.cpp

gcmutils.o: gcmutils.cpp gcmutils.h \
		../../Qt/5.8/gcc_64/include/QtCore/QObject \
		../../Qt/5.8/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.8/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		securityfunctions.h \
		libs/cipher.h \
		libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/aes.h \
		libs/sha512.h \
		libs/gcm.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonDocument \
		../../Qt/5.8/gcc_64/include/QtCore/qjsondocument.h \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonvalue.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonObject \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonobject.h \
		libs/entropy.h \
		libs/sha256.h \
		libs/threading.h \
		libs/havege.h \
		libs/ctr_drbg.h \
		../../Qt/5.8/gcc_64/include/QtCore/QDebug \
		../../Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.8/gcc_64/include/QtCore/qset.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/QDataStream \
		../../Qt/5.8/gcc_64/include/QtCore/qdatastream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gcmutils.o gcmutils.cpp

securityfunctions.o: securityfunctions.cpp securityfunctions.h \
		libs/cipher.h \
		libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/aes.h \
		libs/sha512.h \
		libs/gcm.h \
		../../Qt/5.8/gcc_64/include/QtCore/QDebug \
		../../Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.8/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.8/gcc_64/include/QtCore/qset.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o securityfunctions.o securityfunctions.cpp

aes.o: libs/aes.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/aes.h \
		libs/padlock.h \
		libs/aesni.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o aes.o libs/aes.c

aesni.o: libs/aesni.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/aesni.h \
		libs/aes.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o aesni.o libs/aesni.c

gcm.o: libs/gcm.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/gcm.h \
		libs/cipher.h \
		libs/aesni.h \
		libs/aes.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o gcm.o libs/gcm.c

sha512.o: libs/sha512.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/sha512.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sha512.o libs/sha512.c

cipher.o: libs/cipher.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/cipher.h \
		libs/cipher_internal.h \
		libs/gcm.h \
		libs/ccm.h \
		libs/cmac.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o cipher.o libs/cipher.c

padlock.o: libs/padlock.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/padlock.h \
		libs/aes.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o padlock.o libs/padlock.c

platform.o: libs/platform.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o platform.o libs/platform.c

ccm.o: libs/ccm.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/ccm.h \
		libs/cipher.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ccm.o libs/ccm.c

cmac.o: libs/cmac.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/cmac.h \
		libs/cipher.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o cmac.o libs/cmac.c

cipher_wrap.o: libs/cipher_wrap.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/cipher_internal.h \
		libs/cipher.h \
		libs/aes.h \
		libs/arc4.h \
		libs/camellia.h \
		libs/des.h \
		libs/blowfish.h \
		libs/gcm.h \
		libs/ccm.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o cipher_wrap.o libs/cipher_wrap.c

arc4.o: libs/arc4.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/arc4.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o arc4.o libs/arc4.c

camellia.o: libs/camellia.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/camellia.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o camellia.o libs/camellia.c

blowfish.o: libs/blowfish.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/blowfish.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o blowfish.o libs/blowfish.c

des.o: libs/des.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/des.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o des.o libs/des.c

threading.o: libs/threading.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/threading.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o threading.o libs/threading.c

entropy_poll.o: libs/entropy_poll.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/entropy.h \
		libs/sha512.h \
		libs/sha256.h \
		libs/threading.h \
		libs/havege.h \
		libs/entropy_poll.h \
		libs/timing.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o entropy_poll.o libs/entropy_poll.c

ctr_drbg.o: libs/ctr_drbg.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/ctr_drbg.h \
		libs/aes.h \
		libs/threading.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ctr_drbg.o libs/ctr_drbg.c

timing.o: libs/timing.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/platform.h \
		libs/platform_time.h \
		libs/timing.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o timing.o libs/timing.c

havege.o: libs/havege.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/havege.h \
		libs/timing.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o havege.o libs/havege.c

entropy.o: libs/entropy.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/entropy.h \
		libs/sha512.h \
		libs/sha256.h \
		libs/threading.h \
		libs/havege.h \
		libs/entropy_poll.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o entropy.o libs/entropy.c

bignum.o: libs/bignum.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/bignum.h \
		libs/bn_mul.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o bignum.o libs/bignum.c

ripemd160.o: libs/ripemd160.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/ripemd160.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ripemd160.o libs/ripemd160.c

sha1.o: libs/sha1.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/sha1.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sha1.o libs/sha1.c

sha256.o: libs/sha256.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/sha256.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sha256.o libs/sha256.c

md2.o: libs/md2.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/md2.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o md2.o libs/md2.c

md4.o: libs/md4.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/md4.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o md4.o libs/md4.c

md5.o: libs/md5.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/md5.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o md5.o libs/md5.c

md_wrap.o: libs/md_wrap.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/md_internal.h \
		libs/md.h \
		libs/md2.h \
		libs/md4.h \
		libs/md5.h \
		libs/ripemd160.h \
		libs/sha1.h \
		libs/sha256.h \
		libs/sha512.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o md_wrap.o libs/md_wrap.c

asn1parse.o: libs/asn1parse.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/asn1.h \
		libs/bignum.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o asn1parse.o libs/asn1parse.c

md.o: libs/md.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/md.h \
		libs/md_internal.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o md.o libs/md.c

oid.o: libs/oid.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/oid.h \
		libs/asn1.h \
		libs/bignum.h \
		libs/pk.h \
		libs/md.h \
		libs/rsa.h \
		libs/threading.h \
		libs/ecp.h \
		libs/ecdsa.h \
		libs/cipher.h \
		libs/x509.h \
		libs/platform.h \
		libs/platform_time.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o oid.o libs/oid.c

rsa.o: libs/rsa.c libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/rsa.h \
		libs/bignum.h \
		libs/md.h \
		libs/threading.h \
		libs/oid.h \
		libs/asn1.h \
		libs/pk.h \
		libs/ecp.h \
		libs/ecdsa.h \
		libs/cipher.h \
		libs/x509.h \
		libs/platform.h \
		libs/platform_time.h \
		libs/sha1.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o rsa.o libs/rsa.c

rsautils.o: rsautils.cpp rsautils.h \
		libs/entropy.h \
		libs/config.h \
		libs/target_config.h \
		libs/check_config.h \
		libs/sha512.h \
		libs/sha256.h \
		libs/threading.h \
		libs/havege.h \
		libs/ctr_drbg.h \
		libs/aes.h \
		libs/rsa.h \
		libs/bignum.h \
		libs/md.h \
		../../Qt/5.8/gcc_64/include/QtCore/QObject \
		../../Qt/5.8/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.8/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		securityfunctions.h \
		libs/cipher.h \
		libs/gcm.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonDocument \
		../../Qt/5.8/gcc_64/include/QtCore/qjsondocument.h \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonvalue.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonObject \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonobject.h \
		../../Qt/5.8/gcc_64/include/QtCore/QDebug \
		../../Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.8/gcc_64/include/QtCore/qset.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/QDataStream \
		../../Qt/5.8/gcc_64/include/QtCore/qdatastream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rsautils.o rsautils.cpp

buffer.o: buffer.cpp buffer.h \
		../../Qt/5.8/gcc_64/include/QtCore/QObject \
		../../Qt/5.8/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.8/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/QByteArray \
		../../Qt/5.8/gcc_64/include/QtCore/QDataStream \
		../../Qt/5.8/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiodevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buffer.o buffer.cpp

parser.o: parser.cpp parser.h \
		../../Qt/5.8/gcc_64/include/QtCore/QObject \
		../../Qt/5.8/gcc_64/include/QtCore/qobject.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qflags.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		../../Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstring.h \
		../../Qt/5.8/gcc_64/include/QtCore/qchar.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpair.h \
		../../Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		../../Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonDocument \
		../../Qt/5.8/gcc_64/include/QtCore/qjsondocument.h \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonvalue.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonObject \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonobject.h \
		../../Qt/5.8/gcc_64/include/QtCore/QList \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonArray \
		../../Qt/5.8/gcc_64/include/QtCore/qjsonarray.h \
		clientinfo.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/QHostAddress \
		../../Qt/5.8/gcc_64/include/QtNetwork/qhostaddress.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../Qt/5.8/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		../../Qt/5.8/gcc_64/include/QtCore/qhash.h \
		../../Qt/5.8/gcc_64/include/QtCore/qmap.h \
		../../Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		../../Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/5.8/gcc_64/include/QtCore/qvector.h \
		../../Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		../../Qt/5.8/gcc_64/include/QtCore/qset.h \
		../../Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/5.8/gcc_64/include/QtCore/QJsonValue \
		../../Qt/5.8/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parser.o parser.cpp

moc_Connection.o: moc_Connection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Connection.o moc_Connection.cpp

moc_Server.o: moc_Server.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Server.o moc_Server.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

